- .codecov.yml
- .gitignore
- src/Wflow.jl
- src/kinematic_wave.jl
- test/kinematic_wave.jl
- test/runtests.jl
- downloads a NetCDF with test data as grids
- turns this into a directed graph
- computes a topological sort along the graph
- calculates flow along the topological sort and tests result
@verseve this is the single threaded benchmark code, pretty much as-is. We may end up changing some aspects, but I think it's useful to already have this code here, hooked up to some tests. I uploaded the test data to https://github.com/visr/wflow-artifacts/releases to avoid putting it in this repository, though we can move it to another place later as well.
> add the kinematic wave code

- Project.toml
- src/Wflow.jl
- src/config.jl
- test/config.jl
- test/config.toml
- test/runtests.jl
This is just a stub, but good to get some feedback on. I decided to wrap 
the Dict returned by the TOML parser into a Config struct. This way, we 
can easily define functions that operate on the configuration. 
Specifically, I already implemented Base.getproperty, to make it easy to 
get values with dot notation:
```
config.input.time instead of config["input"]["time"]
```
Since TOML is used in the Pkg manager, it is included with it. Officially it is an internal API, but will likely be moved to an official standard library in the future. I noted some examples of TOML syntax that is not yet supported in the example file.
> support TOML configuration files

- docs/make.jl
- src/Wflow.jl
- src/sbm.jl
- src/sbm_model.jl
- src/subsurface_flow.jl
- src/surface_flow.jl
- src/utils.jl
- test/run_sbm.jl
- added overland flow and river flow
- separate directed acyclic graph for river network from land network
- use of NamedTuples to distinguish between networks and lateral models in Model.jl
Now quite some arguments in update function of model (run_sbm.jl). Need to think a bit more if we want to do this differently, for example store this information as part of the sub-models? 
The river information (0=no river, 1=river) is now stored as part of the vertical model. Both overland flow and subsurface flow need this, to calculate the amount of flow to the river based on slope ratio (frac_toriver and function fraction_runoff_toriver). Mapping between different models now explicitly in model update function (units and grid cells (e.g. "index_river")).
> Surface kinwave

- src/hbv_model.jl
- src/sbm_model.jl
- src/utils.jl
- test/run_sbm.jl
- test/runtests.jl
Pits can be added to the drainage network to get flow at the sub-catchment level (no flow between sub-catchments). Convenient for coupling wflow to a network model like RIBASIM.
Test had been added to run_sbm.jl.
Model type should be provided in the TOML config file.
> Graph pits

- src/io.jl
- src/reservoir_lake.jl
changed the order of reducer components. this is now in line with function active_indices(network, key::Tuple). because reservoir and lake parameters also contain "river" in the parameter name, these parameters should be handled first.
> order of reducers for CSV writing

- src/sbm_gwf_model.jl
to convert recharge SBM [mm/ timestep SBM] to [m/day] (recharge rate groundwater) correctly, requires also scaling by timestep SBM
> recharge rate

- src/flow.jl
- src/reservoir_lake.jl
- test/run_sbm.jl
Reservoir inflow did not have correct units [m3/s]. Calculate reservoir inflow [m3] as total sum during model time step, with or without iterations kinematic wave.
> reservoir inflow

- docs/make.jl
- docs/src/lateral/gwf.md
- src/Wflow.jl
- src/bmi.jl
- src/flow.jl
- src/groundwater/aquifer.jl
- src/groundwater/boundary_conditions.jl
- src/groundwater/connectivity.jl
- src/hbv.jl
- src/hbv_model.jl
- src/io.jl
- src/reservoir_lake.jl
- src/sbm.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
- src/utils.jl
- src/vertical_process.jl
- test/bmi.jl
- test/groundwater.jl
- test/io.jl
- test/reservoir_lake.jl
- test/run_hbv.jl
- test/run_sbm.jl
- test/run_sbm_gwf.jl
- test/runtests.jl
- test/testing_utils.jl
This uses the default style. Did this: `using JuliaFormatter; format(".")`
If you want to run this from VS Code, you can use this extension (VS Code Julia currently still has a different default formatter): https://github.com/singularitti/vscode-julia-formatter/
Already went through the diff and I think it's better in almost all cases. Only don't like this so much: https://github.com/Deltares/Wflow.jl/compare/format?expand=1#diff-b6a501ee6fbf026b1fd082d57f38964b960813f58679f4b54485649557bc26e9R102-R107
But perhaps we should just split those lines anyway.
> run JuliaFormatter on all code

- src/flow.jl
- src/hbv_model.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
- src/utils.jl
- test/bmi.jl
- test/run_sbm.jl
Reservoirs and lakes (water bodies) are now handled differently within the kinematic wave, and more in line with the original implementation in Python. Outflow goes to the next downstream river cell (instead of remaining in the cell where the water body is located). Inflow consists of subsurface, land and overland flow. 
The filtering of upstream nodes (water bodies are excluded) is done in the initialization of the model, and stored as part of the network information. This filtering in the update function seemed a bit expensive, and the SBM Models Update benchmark seems faster (hits more often ~700 ms now, instead of ~900 ms).
> River waterbodies

- src/hbv_model.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
- src/sediment_model.jl
If the cyclic data is in there as well, the NCReader also opens the same file, but that is a different handle that is already being closed properly. With this, all files are closed, tested by running a simulation, and before closing the session, moving all input+output data to a different folder. That's how I found this file was left open as well.
> close the staticmaps NetCDF during initialization

- src/Wflow.jl
The starttime needs to change (+ 1 timestep) when running in Delft-FEWS.
> starttime run in fews

- docs/src/structure.md
- docs/src/vertical/sbm.md
- src/io.jl
- test/run_sbm.jl
- test/sbm_config.toml
This is similar to the CSV option. Scalar timeseries are exported to another file than the gridded time series, for allowing import of these timeseries by Delft-FEWS (General Adapter).
> export NetCDF scalar timeseries

- .github/workflows/CI.yml
- Project.toml
- docs/src/changelog.md
- docs/src/config.md
- src/Wflow.jl
- src/bmi.jl
- src/hbv_model.jl
- src/horizontal_process.jl
- src/io.jl
- src/sbm.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
- src/sediment.jl
- src/sediment_model.jl
- src/utils.jl
- test/bmi.jl
- test/hbv_config.toml
- test/horizontal_process.jl
- test/io.jl
- test/run_hbv.jl
- test/run_sbm.jl
- test/run_sediment.jl
- test/runtests.jl
- test/sbm_config.toml
- test/sbm_gw.toml
- test/sediment_config.toml
Previously we accepted x and y dimensions in either order, and adapted to that internally. However, some issues arose with other variants present in and between the netCDF inputs that made it clear that we need to support more variants. Some benchmarking showed that moving away from in place netCDF loading hardly affected performance. So to be both more flexible, and reduce some internal code complexity, we treat the data at entry to always follow the dimension order (x, y, layer, time), and to have increasing axes for each dimension.
> use a single internal dimension order with increasing axes

- src/io.jl
This will now give:
```
ERROR: inactive cell found in requested CSV output
map "gauges" value 358 for parameter lateral.river.q_av
```
Before it was a bit too cryptic what area v was and why this error was thrown.
> improve error message for CSV reducer

- test/Project.toml
- test/benchmark.jl
- test/run_hbv.jl
- test/run_sbm.jl
- test/run_sbm_gwf.jl
- test/run_sediment.jl
- test/runtests.jl
- test/testing_utils.jl
I'll merge this quickly to get CI passing again. This seems to be the main cause of testing issues on multiple threads.
Benchmarks will be enabled again soon, but run separately as part of
https://juliaci.github.io/PkgBenchmark.jl/stable/. However they also need to be revised to make sure they don't keep running the same timestep in each benchmark iteration.
> don't run benchmarks during CI

- src/io.jl
This adds some attributes according to the CF conventions to the output grid netCDF files. This should make it easier for applications to recognize the spatial axes, other than guessing the name.
http://cfconventions.org/cf-conventions/cf-conventions.html#grid-mappings-and-projections
http://cfconventions.org/cf-conventions/cf-conventions.html#coordinate-types
> add standard_name and axis to NetCDF coordinates

- docs/src/changelog.md
- src/groundwater/boundary_conditions.jl
- src/reservoir_lake.jl
- src/sbm_gwf_model.jl
- test/groundwater.jl
- test/run_sbm_gwf.jl
Link the drain flux from GroundwaterFlow to the overland flow component (sbm_gwf_model.jl). This flux was only linked to the river kinematic wave. After some discussion with @laurenebouaziz and @Huite we decided to link the drain flux only to the overland flow component. There is also a check if drains are located where overland does not occur (because of the river width. the overland flow width may be set to zero), and if this is the case these drain locations are removed.
> fix drains

- src/io.jl
- test/io.jl
- test/sbm_config.toml
After #154 the variables that had aliases could no longer also have modifiers in the TOML, since `get_alias` returned a Dict instead of a Config. This fixes that and adds tests.
> fix get_alias for variables with expanded definition

- docs/src/changelog.md
- docs/src/lateral/kinwave.md
- src/flow.jl
- src/hbv_model.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
- test/bmi.jl
- test/run_hbv.jl
- test/run_sbm.jl
- test/run_sbm_gwf.jl
When alpha is updated in the kinematic wave with the new h value (wetted perimeter), this creates water balance errors.
To avoid these errors and have a more closed water balance the alpha value is now fixed. A bankfull height map can be provided for the river part to calculate the fixed alpha value (based on half bankfull height). For the land part the wetted perimeter is based on the flow width only.
> Option to fix alpha value in the kinematic wave

- docs/src/changelog.md
- docs/src/vertical/parameters.md
- docs/src/vertical/sbm.md
- src/sbm.jl
- src/sbm_gwf_model.jl
- test/bmi.jl
- Changed the scaling of capillary rise, now based on a common approach found in literature.
- Fixed conversion of boundaries of `GroundwaterFlow` [m3/d] to m3/s in `sbm_gwf` model concept (conversion was based on model time step and should be based on basetimestep (86400 s).
> Fix subdaily sbm gwf

- docs/src/changelog.md
- docs/src/config.md
- src/hbv_model.jl
- src/io.jl
- src/reservoir_lake.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
- src/sediment_model.jl
- test/hbv_config.toml
- test/io.jl
- test/reservoir_lake.jl
- test/runtests.jl
- test/sbm_config.toml
- test/sbm_gw.toml
- test/sbm_gwf_config.toml
- test/sbm_simple.toml
- test/sediment_config.toml
Until now, the paths to the files were all either absolute or relative to the TOML. This makes is flexible because you can point to wherever you want. One downside, compared to the more rigid approach used before, is that it makes it hard to try quickly send all output to a new directory when trying things out, as you have to change all the output paths in the TOML.
This should relieve that, as you can now just add a `dir_input` and `dir_output` key in the TOML. If they are not added, nothing changes, so this is not breaking. These folders are only used for paths that are not absolute. `dir_input` and `dir_output` can also be absolute if needed.
> add support for dir_input and dir_output

- docs/src/changelog.md
- src/flow.jl
- src/hbv_model.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
When the surface flow width for overland flow is zero, h of the kinematic wave should not be calculated, otherwise this results in NaN values.
> fix surface flow width

- src/hbv_model.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
- src/sediment_model.jl
- src/utils.jl
If the fill value of the netCDF is NaN, NCDatasets will make it a missing. But if that is not the case and we don't want missings, I cannot think of any case where we would want NaN.
This will work for instance to catch NaN values if they are present in the river width with the current call to ncread:
```julia
ncread(nc, param(config, "input.lateral.river.width"); type = Float, fill = 0)
```
> disallow NaN in ncread if allow_missing=false

- docs/src/changelog.md
- src/flow.jl
- src/utils.jl
Fixing issues https://github.com/Deltares/Wflow.jl/issues/191 and https://github.com/Deltares/Wflow.jl/issues/181.
Issue https://github.com/Deltares/Wflow.jl/issues/181 is fixed by checking if the NetCDF variable `var` has dimension `time` in the `ncread` function. If this is the case, it is a cyclic parameter that is handled by the `update_cyclic!` function.
> Fix issues #181 and #191

- docs/src/changelog.md
- docs/src/lateral/kinwave.md
- docs/src/lateral/kinwave_params.md
- src/flow.jl
- test/run_sbm.jl
> rename h_bankfull to bankfull_depth

- docs/src/changelog.md
- docs/src/model_docs/params_lateral.md
- src/flow.jl
- src/horizontal_process.jl
- src/sbm_model.jl
- test/bmi.jl
The unit of lateral subsurface flow (ssf) has been changed from m3/Δt to m3/day, where Δt is the model timestep. Other flow variables are already stored independently from Δt, this allows for easier interpretation and to use states independently of Δt.
> Change unit of lateral subsurface flow (ssf)

- docs/src/changelog.md
- docs/src/user_guide/step2_settings_file.md
- src/io.jl
Support using the deflatelevel option when writing the netcdf output data. This option is currently only available for the gridded NetCDF data (so not for the states and scalar output), as this file can become very large. 
The option can be specified in the `[output]` section of the TOML file, via the `compressionlevel` keyword. A value of 0 (default) indicates no compression, and values between 1 and 9 indicate increasing levels of compression, but at the cost of increased computation times. 
Some tests for the Moselle and the Rhine showed that file size reduction is already substantial when using `compressionlevel = 1` (file sizes are reduced by a factor of 4-5), while the total computation time has increased by 5-25%, depending on the basin. Using `compressionlevel = 9`, files are only …
> Support compression of NetCDF file

- docs/src/changelog.md
- src/logging.jl
Fix the `No such file or directory` error when Wflow tries to write a log file in a (not yet) existing directory (see https://github.com/Deltares/Wflow.jl/issues/209). Now, the directory is created before trying to create the log file.
> Create dir before creating log file

- docs/make.jl
- docs/src/changelog.md
- docs/src/model_docs/lateral/kinwave.md
- docs/src/model_docs/lateral/local-inertial.md
- docs/src/model_docs/lateral/waterbodies.md
- src/flow.jl
- src/reservoir_lake.jl
- src/sbm_model.jl
- src/utils.jl
- test/horizontal_process.jl
- test/run_sbm.jl
Inflow (external) added to local inertial 1D-2D model.
Fixed couple of issues related to reservoir and lake locations, and added check (limit flow (set to zero)) when water is not available.
> Local inertial 1D-2D: inflow, reservoirs and lakes

- docs/src/changelog.md
- src/io.jl
There were no actual missing values, but setting the attribute itself is also not allowed.
Quoting https://cfconventions.org/cf-conventions/cf-conventions.html#attribute-appendix
> `_FillValue`: Allowed for auxiliary coordinate variables but not allowed for coordinate variables.
> remove _FillValue from coordinate variables

- Project.toml
- test/io.jl
- test/runtests.jl
This enables some extra tests that can be very useful: 
https://juliatesting.github.io/Aqua.jl/dev/
Also cleans up the testing dependencies a bit. There is no need to specify them separately under extras if they are also a regular dependency. And LoggingExtras re-exports the Logging stdlib.
> add extra tests from Aqua

- docs/src/changelog.md
- src/io.jl
Fixed an issue where the `_FillValue` attribute in the time dimension of the forcing file causes an error, as the `get_at` function was unable to dispatch due to unexpected types. This addition checks (if the `_FillValue`  is present) whether there are actual missing values in the time dimension. If this is the case, an error is thrown, otherwise the dates are converted to the correct type for the `get_at` function.
> Allow for _FillValue in time dimension

- docs/src/changelog.md
- src/bmi.jl
- test/bmi.jl
(includes the commits from #245)
As long as BMI is used properly, this shouldn't be breaking. This is the same behavior as Modflow and Ribasim, and the [BMI docs](https://bmi.readthedocs.io/en/stable/#get-start-time) state:
> The start time in BMI is typically defined to be 0.0.
> BMI use simulation starttime as t = 0, not 1970

- docs/src/changelog.md
- src/bmi.jl
- test/bmi.jl
Perhaps this was originally done since it doesn't need any information from the model instance, but since this is the only one, this looks more like a bug to me.
> define BMI.get_time_units on model instance

- docs/src/changelog.md
- docs/src/user_guide/step2_settings_file.md
- src/io.jl
- test/io.jl
The option to take the sum over a certain region was not possible. This allows the user to use `sum` as a reducer. This can be useful in cases where (for example) we want to sum the amount of water flowing into the river for each subcatchment/region.
> Add `sum` to reducer options

- docs/src/changelog.md
- docs/src/model_docs/params_vertical.md
- src/sbm.jl
- src/vertical_process.jl
Fixes #299
The amount of computed `throughfall` and `stemflow` in the modified Rutter interception model could become larger than the precipitation input (water balance issue), because the sum of the stemflow partitioning coefficient `pt` and free throughfall coefficient `p` could get larger than 1. In addition, the net interception (`netinterception`) was not computed correctly: the first drainage term `dd` was subtracted from precipitation (as part of `throughfall`), while `dd` is controlled by a change in the canopy storage capacity `cmax` over time (e.g. because of a change in leaf area index LAI), and thus not part of the precipitation input. This could result in a negative `netinterception`: 
```julia
netinterception = precipitation - throughfall - stemflow
````
Finally, the …
> Fix rutter interception

- docs/src/changelog.md
- docs/src/user_guide/step2_settings_file.md
- src/io.jl
- src/reservoir_lake.jl
- test/runtests.jl
Fixes #277
Support different cyclic time inputs, for example monthly and daily. The time dimension name of the cyclic parameter in the input netCDF file should start with "time" (to allow for different time vectors).
> Cyclic times

- docs/src/changelog.md
- docs/src/model_docs/params_lateral.md
- src/flow.jl
- src/sbm.jl
Issue was not reported.
Include `kvfrac` in the computation of vertical saturated hydraulic conductivity at the bottom of the soil layer, so it is consistent with the unsaturated vertical flow computation.
> Kvfrac leakage

- docs/src/changelog.md
- src/bmi.jl
- test/bmi.jl
No issue reported.
See comment first commit and updated changelog.
> BMI `get_grid_size` function

- docs/src/changelog.md
- docs/src/model_docs/params_vertical.md
- src/sbm.jl
- src/sbm_model.jl
- test/bmi.jl
- test/run_sbm.jl
Fixes #281 
Simple added it to the SBM struct, added the h_av flow.jl for land and river (with riverfrac)
It's done in millimeters [mm]
> Total Water Storage

- docs/src/changelog.md
- docs/src/model_docs/params_lateral.md
- src/flow.jl
- src/reservoir_lake.jl
- test/bmi.jl
- test/reservoir_lake.jl
Fixes #329
See the updated changelog.
> Check lake balance

- docs/src/changelog.md
- src/sbm_model.jl
Fixes #357 
Fixed the for loop for the local inertial routing of the land component in the `set_states` function of model type `sbm`.
> Fix `set_states` function of model type `sbm`

- docs/src/changelog.md
- docs/src/intro/use_cases.md
- docs/src/model_docs/model_configurations.md
- docs/src/model_docs/params_lateral.md
- docs/src/model_docs/structures.md
- docs/src/user_guide/additional_options.md
- docs/src/user_guide/install.md
- docs/src/user_guide/intro.md
- docs/src/user_guide/model-setup.md
- docs/src/user_guide/sample_data.md
- docs/src/user_guide/step1_requirements.md
- docs/src/user_guide/step2_settings_file.md
- docs/src/user_guide/step3_input_data.md
- docs/src/user_guide/step4_running.md
- docs/src/user_guide/step5_output.md
- src/Wflow.jl
- src/bmi.jl
- src/flextopo_model.jl
- src/hbv_model.jl
- src/io.jl
- src/sbm.jl
- src/sbm_gwf_model.jl
- src/sbm_model.jl
- src/sediment_model.jl
- src/utils.jl
- test/bmi.jl
- test/io.jl
This PR updates the spelling and grammar in the User guide section of the Wflow documentation.
This resolves one of the tasks in issue #377, namely the update of the User guide section.\
As I joined the team this week I have been reading the documentation in sequential order from front to back and along the way I commit languages changes.
> Improve spelling and grammar in the user guide

- docs/src/changelog.md
- docs/src/model_docs/params_vertical.md
- server/test/client.jl
- src/flow.jl
- src/sbm.jl
- test/bmi.jl
- test/run_sbm.jl
Fixes #372 
See https://github.com/Deltares/Wflow.jl/issues/372.
> Remove lower limit of zero for `sbm.runoff`

- docs/src/changelog.md
- docs/src/model_docs/params_vertical.md
- docs/src/model_docs/vertical/sbm.md
- server/test/client.jl
- src/sbm.jl
- test/bmi.jl
- test/run_sbm.jl
- test/run_sbm_gwf.jl
Fixes #374
See issue https://github.com/Deltares/Wflow.jl/issues/374
> `SBM` evaporation and use of fractions

- docs/src/changelog.md
- src/bmi.jl
- test/bmi.jl
Fixes #386 
`BMI.update_until` could throw an `InexactError: Int64` caused by a not whole number. This is fixed by using `divrem` for the computation of the number of  `steps` in `BMI.update_until`, an error is thrown when the absolute remainder is larger than `eps()`. An error is also thrown when `steps` is a negative number.
> Fix `BMI.update_until` (`InexactError: Int64`)

- docs/src/changelog.md
- docs/src/model_docs/lateral/local-inertial.md
- docs/src/model_docs/model_configurations.md
- docs/src/user_guide/additional_options.md
- docs/src/user_guide/model-setup.md
Fixes #395 
Fixed broken internal and external links in docs. 
Improved the description of different model configurations in `model-setup.md`, also in relation to `hydromt_wflow` in docs.
> Fix broken doc links

- .gitignore
- pixi.toml
- utils/env_setup.bat
- utils/env_setup.sh
Cherry-pick from Master: Stop using local JULIAUP_DEPOT_PATH
> Stop using local JULIAUP_DEPOT_PATH (#438)

- docs/src/user_guide/intro.md
Fixes #457 
Propose some editorial changes while reading the doc.
> Editorial changes on user_guide/intro.md

- docs/src/model_docs/shared_concepts.md
Changed the sentence:
> The definition of glacier boundaries and initial volume is defined in three parameters. 
to:
> The definition of glacier boundaries and initial volume is defined by two parameters.
Fixes #477 
Changed the docs
> Correction glacier documentation

- build/create_binaries/add_metadata.jl
- pixi.toml
It is not part of the Wflow entry in the Manifest.toml file and as a result the build fails.
Fixes #479
> Remove git-tree-sha1 from metadata

- docs/src/changelog.md
- server/src/bmi_service.jl
- server/src/server.jl
- src/bmi.jl
- test/bmi.jl
> Return nothing from mutating BMI functions

- docs/model_docs/vertical/sbm.qmd
- docs/model_docs/vertical/shared_processes.qmd
> move snowfall figure

- docs/model_docs/parameters_vertical.qmd
- docs/model_docs/vertical/shared_processes.qmd
- docs/user_guide/model_config.qmd
- src/glacier/glacier.jl
- src/glacier/glacier_process.jl
- test/sbm_gwf_piave_demand_config.toml
- test/sbm_piave_config.toml
- test/sbm_piave_demand_config.toml
Fixes #511 
See issue #511. Also fixed the use of `tt` (should be `ttm`) for describing snow melt in shared_process.qmd.
> Rename glacier parameter `g_tt` to `g_ttm`

- Manifest.toml
- build/create_binaries/Manifest.toml
- build/wflow_cli/Manifest.toml
- docs/Manifest.toml
- pixi.lock
- pixi.toml
- server/Manifest.toml
The main benefit is that the Julia update from 1.10.5 to 1.10.7 will fix random failures on TeamCity related to artifact installation filesystem issues. See https://discourse.julialang.org/t/error-ioerror-rm-c-users-35879-julia-artifacts-jl-wek1vy-bin-directory-not-empty-enotempty/123142/5?u=visr if you are interested in details.
> Update Julia and Pixi manifests

- Manifest.toml
- build/create_binaries/Manifest.toml
- build/wflow_cli/Manifest.toml
- docs/Manifest.toml
- pixi.toml
- server/Manifest.toml
The pixi.toml now installs julia 1.11.3. I directly updated all manifests such that they are resolved with this version. Note that in the Wflow.jl's Project.toml compat it still says `julia = "1.10"`, meaning the LTS release is still supported. We are not using any Julia 1.11+ features yet. It might be a good idea to make sure that 1.10 is also tested in CI, and not only 1.11, but that should be a separate PR.
> Update dev environment to Julia 1.11

- src/utils.jl
- test/io.jl
Should resolve to `network.river.indices` (and not `network.land.indices`).
> Fix active indices floodplain from `network`

- src/Wflow.jl
- src/io.jl
- src/sbm_model.jl
- src/sediment_model.jl
- test/run_sbm_gwf.jl
Optional TOML sections: `time` and `logging`.
> Check optional sections in TOML file

- docs/changelog.qmd
- src/groundwater/aquifer.jl
- src/groundwater/boundary_conditions.jl
- src/sbm_gwf_model.jl
- test/groundwater.jl
> Model type `sbm_gwf`: limit river flux to groundwater

- test/sbm_piave_demand_config.toml
One of the tomls had an incorrect `[output.csv]` section. This PR fixes that
> Small fix in test/example toml

- build/create_binaries/Project.toml
- build/wflow_cli/Project.toml
- docs/Project.toml
- pixi.toml
- server/Project.toml
Related to https://github.com/Deltares/Wflow.jl/issues/577#issuecomment-2796910094.
This doesn't do much directly since we have all Manifest.toml files checked in, and they point to the right directory for Wflow. But if you'd remove them and reinstantiate, you'd get Wflow from the registry instead of the one in this repo. Hence it is convenient to specify where to find Wflow.
> Add Wflow source location to Project.tomls

- docs/getting_started/install.qmd
The current link https://julialang.org/downloads/#current_stable_release goes to the old way to install. As you can see on top of that page the current recommended way is with `juliaup`, which is described here: https://julialang.org/install/.
It is not the official docs, but for new users I think https://modernjuliaworkflows.org/writing/#installation is more accessible, so I link there instead.
> Edit "Installing as Julia package"

- Wflow/src/routing/routing_process.jl
- Wflow/src/sbm.jl
Fixes #651 
Dispatch lateral snow transport on `snow` model type. This is consistent with simulating snow dynamics and avoids running lateral snow transport when snow modelling is not included (`snow__flag = false`) while snow transport is included (`snow_gravitional_transport__flag = true`) and as a result the following `type NoSnowModel has no field variables` error is not thrown.
> Dispatch lateral snow transport function

- Wflow/src/routing/subsurface.jl
- docs/changelog.qmd
This was not correct for a sub-daily model timestep.
Fixes #661
> Fix unit conversion `kv_0` to `kh_0`

- pixi.toml
No issue, build and test on TeamCity were failing due to missing project instantiates. I guess last time they ran successfully due to cached environments (?). 
I have added project instantiate dependencies to the relevant pixi tasks
> Add instantiate to build-cli and test-cli tasks
