Deltares/Wflow.jl

Project.toml, src/Wflow.jl, src/sbm.jl, src/utils.jl, src/vertical_process.jl, test/runtests.jl, test/sbm.jl, test/vertical_process.jl
sbm_update includes:
- unit tests for vertical processes
- functions have docstrings and comments were added throughout the code
- SBM struct contains all variables (fields)
Suggest to link to parts of model struct in other branch(es):
- reader/writer (forcing (also lai clim), model variables)
- io (TOML file)
- lateral models
=> Sbm update

src/sbm.jl, src/vertical_process.jl, test/vertical_process.jl
Just added two vertical functions (including unit tests):
- glacier_hbv
- rainfall_interception_modrut
=> Vertical funcs

src/hbv.jl, src/hbv_model.jl, src/sbm.jl, src/sbm_model.jl
Glacier parameters added for sbm and hbv models.
=> glacier parameters for sbm and hbv

src/flow.jl, src/utils.jl
Otherwise this gets a "cannot reduce empty collection" error as found by @markhegnauer.
=> support rivers with no upstream nodes

src/flow.jl
support rivers with no upstream nodes was fixed for lateral subsurface flow, now also fixed for overland flow.
=> overland flow and no upstream nodes

docs/src/model/hbv.md, docs/src/model/sbm.md, docs/src/structure.md
The mapping of model variables (of vertical and lateral concepts) is described in more detail. This is important for understanding the configuration TOML file (e.g. how to extract variables from the Model struct).
=> docs mapping model variables

.github/workflows/CI.yml, .github/workflows/Documenter.yml
Test on MacOS, set version to 1.5, the minimum supported julia version for Wflow.
=> split CI and Documenter

src/sbm_gwf_model.jl
calculation of drain flux to river should be optional, depending in drains setting of model
=> fix update sbm_gwf (drains = false)

src/reservoir_lake.jl
small fix, doy is used to lookup the column in a HQ table, Q has as maximum of 365.
=> doy should not exceeed 365

src/io.jl
Apparently this already worked fine. Part of #91.
=> remove unneeded _FillValue restriction

docs/src/changelog.md, docs/src/lateral/sediment.md, src/sediment.jl, test/run_sediment.jl, test/runtests.jl, test/sediment_config.toml
Updated sediment.jl:
- corrected a bug in sediment deposition in the river
- new deposition process for coarse sediment in the reservoirs with a new parameter restrapefficiency
- new variables in the sediment structs so that more variables can be sevaed as outputs
=> Sediment update

src/io.jl
This is already being done for the NetCDF output:
https://github.com/Deltares/Wflow.jl/blob/8cf3eac8618eb6fcdbc8a2c1286cf848d3a35a16/src/io.jl#L282-L284
=> create directory if needed for output CSV

docs/make.jl, docs/src/bmi.md, docs/src/changelog.md, src/bmi.jl, src/flow.jl, src/hbv_model.jl, src/io.jl, src/sbm.jl, src/sbm_gwf_model.jl, src/sbm_model.jl, src/sediment.jl, test/bmi.jl, test/sbm_gw.toml
To couple an external groundwater model to the SBM model it is convenient to update the SBM model in parts. The update function of BMI now exposes a function to 1) update the model until recharge, and 2) update the model after update of groundwater model.
=> update SBM model in parts (bmi)

README.md, docs/Project.toml, docs/src/index.md
https://deltares.github.io/Wflow.jl/previews/PR143/
=> docs: add ColPrac link, and link to source

docs/src/cli.md, docs/src/fews.md, docs/src/index.md, docs/src/quick-start.md
=> add JULIA_NUM_THREADS to wflow_cli docs

src/reservoir_lake.jl
@verseve could you check if these changes seem ok?
I will also let you know after the weekend how the test run goes.
=> fix outflow calc when negative value in log

src/subdomains.jl, test/run_sbm.jl, test/runtests.jl
This still needs a test. Currently the test models have single basins.
=> fix multithreading for multiple basins

docs/src/quick-start.md
describe multi-threading functionality as experimental
=> docs mult-threading

docs/src/changelog.md, src/io.jl, test/io.jl
fixed use of abs path for the forcing file (was broken)
=> abs path forcing

docs/src/changelog.md, src/bmi.jl, src/hbv.jl, src/io.jl, src/sbm.jl
I ran `report_package` from JET. Most identified issues could be ignored, but it did find a few actual mistakes, which is very helpful.
https://aviatesk.github.io/JET.jl/dev/jetanalysis/#JET.report_package
Would be nice to do the optimization analysis in another PR: https://aviatesk.github.io/JET.jl/dev/optanalysis/.
=> fix a few issues identified by JET

docs/src/changelog.md, src/flow.jl, src/io.jl, src/sbm.jl, test/io.jl
By accepting it as an alias, and giving a warning about the name change.
=> don't break if h_bankfull is still used

.zenodo.json, docs/src/intro/publications.md
=> Update list of contributors docs and zenodo

docs/src/changelog.md, docs/src/model_docs/lateral/waterbodies.md, src/reservoir_lake.jl, test/reservoir_lake.jl
Issue was not reported.
See changelog and first commit.
=> Modified puls

docs/src/model_docs/params_lateral.md
=> Update sediment parameters

src/sediment.jl
=> Also update sediment units in struct

docs/src/model_docs/params_lateral.md, src/sediment.jl
=> Fix docs sediment concentration parameters

docs/src/index.md, docs/src/intro/use_cases.md
This PR updates the spelling and grammar in the Introduction section of the Wflow documentation.
This resolves one of the tasks in issue #377, namely the update of the Introduction section.\
As I joined the team this week I have been reading the documentation in sequential order from front to back and along the way I commit languages changes.
=> Improve spelling and grammar in the introduction

docs/src/model_docs/model_configurations.md, docs/src/model_docs/shared_concepts.md, docs/src/model_docs/vertical/sbm.md, docs/src/model_docs/vertical/sediment.md
This PR updates the spelling and grammar in the Modeling documentation section of the Wflow documentation.
This resolves one of the tasks in issue https://github.com/Deltares/Wflow.jl/issues/377, namely the update of the Modeling documentation section.
As I joined the team this week I have been reading the documentation in sequential order from front to back and along the way I commit languages changes.
=> Improve spelling and grammar in the modeling documentation

build/create_binaries/download_test_data.jl, docs/src/changelog.md, src/states.jl, test/io.jl, test/run_sbm_gwf.jl, test/runtests.jl, test/sbm_gwf_config.toml
=> Fix required states `sbm_gwf` model type

docs/src/model_docs/lateral/sediment_flux.md
Minor typo fixes and updates for the sediment model documentation.
=> Update sediment model documentation

docs/src/changelog.md, src/sbm_gwf_model.jl
=> Quick boundary fix

.gitignore, pixi.toml, utils/env_setup.bat, utils/env_setup.sh
Same as https://github.com/Deltares/Ribasim/pull/1614
=> Stop using local JULIAUP_DEPOT_PATH

Manifest.toml, Project.toml, build/create_binaries/Manifest.toml, build/wflow_cli/Manifest.toml, build/wflow_cli/Setup/Installer/Application.Setup.wixproj, docs/src/changelog.md, server/Manifest.toml
Bump version and update Manifest.toml files.
=> Prepare release v0.8.0

docs/src/intro/use_cases.md
Fixes #455 455
Proposed fixes and revisions.
Feel free to select proposed changes when merging.
=> Editorial review on user case doc

docs/src/user_guide/install.md
Fixes #459 
Editorial changes were proposed.
=> Editorial changes on user guide/install.md

docs/src/user_guide/step1_requirements.md
Editorial changes to user_guide/step1_requirements.md
=> Editorial changes to user_guide/step1_requirements.md

docs/src/user_guide/step2_settings_file.md
Editorial changes to `user case/step2_ requirements.md`
=> Editorial changes to user case/step2_ requirements.md

src/bmi.jl, test/bmi.jl
=> Fix warn typo

src/standard_name.jl
=> Fix duplicate standard name 

docs/changelog.qmd, src/sbm_gwf_model.jl, src/states.jl, src/surfacewater/runoff.jl, test/io.jl, test/run.jl, test/run_sbm_gwf.jl, test/run_sbm_gwf_piave.jl, test/sbm_config.toml, test/sbm_gw.toml, test/sbm_gwf_config.toml, test/sbm_gwf_piave_demand_config.toml, test/sbm_piave_config.toml, test/sbm_piave_demand_config.toml, test/sbm_swf_config.toml
=> Change use of routing water depth `h_av` to `h` 

test/run_sediment.jl, test/runtests.jl
=> Sediment model state file

Wflow/src/demand/water_demand.jl, Wflow/src/routing/surface_kinwave.jl, Wflow/src/routing/surface_local_inertial.jl, docs/changelog.qmd
=> Local inertial routing: limit negative external inflow

Wflow/src/standard_name.jl, docs/model_docs/land/landhydrology_sbm.qmd, docs/model_docs/parameters_intro.qmd, docs/model_docs/parameters_landhydrology_sbm.qmd, docs/model_docs/parameters_routing.qmd, docs/model_docs/routing/local-inertial.qmd
=> Extend standard names

Wflow/src/groundwater/aquifer.jl, Wflow/src/routing/subsurface.jl, Wflow/src/snow/snow.jl, Wflow/src/soil/soil.jl, Wflow/src/vegetation/parameters.jl, Wflow/test/run_sbm.jl, Wflow/test/run_sbm_gwf.jl, Wflow/test/sbm_gwf_config.toml, docs/changelog.qmd, docs/model_docs/parameters_intro.qmd, docs/model_docs/parameters_landhydrology_sbm.qmd, docs/model_docs/parameters_routing.qmd, docs/user_guide/required_files.qmd, server/test/client.jl
=> Check optional parameters

Wflow/src/routing/surface_kinwave.jl, Wflow/src/routing/surface_local_inertial.jl, Wflow/src/standard_name.jl, Wflow/test/routing_process.jl, Wflow/test/run_sbm.jl, docs/changelog.qmd, docs/model_docs/parameters_routing.qmd
=> Support computation and output of actual river water abstraction

Wflow/src/io.jl, Wflow/src/sbm_model.jl, Wflow/src/soil/soil.jl, docs/changelog.qmd, docs/getting_started/install.qmd, docs/getting_started/running_wflow.qmd, docs/model_docs/land/landhydrology_sbm.qmd, docs/model_docs/model_configurations.qmd, docs/model_docs/model_settings.qmd
=> Fix installation instructions given new location of Wflow source directory

docs/getting_started/download_example_models.qmd
=> fix broken links

pixi.toml
Same as https://github.com/Deltares/Ribasim/pull/2324
=> Don't reresolve test environment

Wflow/src/vegetation/canopy.jl, docs/changelog.qmd
=> Fix RutterInterception

Wflow/src/io.jl, Wflow/test/run_sbm.jl
=> Add date time info to error message when forcing/cyclic data is missing.

Wflow/src/sbm.jl, Wflow/test/run_sbm.jl
Issue introduced after pre-release rc1.
=> Fix check model setting lateral snow transport
